export const PROJECTS = [
  {
    id: 1,
    title: "SKITRO",
    category: "Full Stack Application",
    slug: "skitro",
    url: "https://v0-skitro.vercel.app/",
    date: "2023",
    color: "#2C3E50", 
    role: "Lead Developer",
    services: "Full Stack Development, 3D Integration",
    location: "Global",
    description: "Skitro is a premium full-stack application focused on delivering high-end 3D animations and visualization tools within a sleek, modern interface. We pushed the boundaries of WebGL performance to ensure seamless interactions.",
    video: "/videos/skitro.mp4",
    image: "/images/image-1.png"
  },
  {
    id: 2,
    title: "COGNITOFLOW",
    category: "Web Application",
    slug: "cognitoflow",
    url: "https://cognitoflow.framer.ai/",
    date: "2023",
    color: "#8E44AD", 
    role: "Frontend Engineer",
    services: "UI/UX Architecture, Framer Motion",
    location: "Remote",
    description: "CognitoFlow is an AI-driven web application designed to streamline complex cognitive tasks into simple, intuitive workflows. The primary challenge was mapping dense AI capabilities into an accessible, beautiful user interface.",
    video: "/videos/cognitoflow.mp4",
    image: "/images/image-2.png"
  },
  {
    id: 3,
    title: "LUMIERE",
    category: "Storefront",
    slug: "lumiere",
    url: "https://v0-luxury-beauty-storefront.vercel.app/",
    date: "2022",
    color: "#16A085", 
    role: "E-Commerce Lead",
    services: "Frontend Development, Performance Optimization",
    location: "Europe",
    description: "Lumière is an ultra-luxury beauty storefront focusing on cinematic product presentation. The goal was to build an e-commerce platform that felt like flipping through a high-end fashion magazine, complete with seamless transitions and massive typography.",
    video: "/videos/lumiere.mp4",
    image: "/images/image-3.png"
  },
  {
    id: 4,
    title: "PREMIERTECH",
    category: "Agency Landing",
    slug: "premiertech",
    url: "https://premiertechagency.netlify.app/",
    date: "2021",
    color: "#C0392B", 
    role: "Creative Developer",
    services: "Web Design, Interactive Development",
    location: "USA",
    description: "Premier Tech Agency required a digital presence that matched their innovative solutions. We built a high-performance landing page characterized by kinetic typography, bold color blocking, and smooth scrolling experiences.",
    video: "/videos/premiertech.mp4",
    image: "/images/image-4.png"
  },
];
